
import { Sector } from './types';

export const SECTORS: Sector[] = ["Statistics", "PublicOpinion", "DomesticCases", "InternationalCases", "Theories", "Stakeholders"];

export const SECTOR_TRANSLATIONS: Record<string, Record<string, string>> = {
  en: { 
    "Statistics": "Statistics & Data", 
    "PublicOpinion": "Public Opinion", 
    "DomesticCases": "Domestic Cases", 
    "InternationalCases": "International Cases", 
    "Theories": "Academic Theories", 
    "Stakeholders": "Stakeholders" 
  },
  ko: { 
    "Statistics": "통계 및 데이터", 
    "PublicOpinion": "여론 및 설문", 
    "DomesticCases": "국내 사례", 
    "InternationalCases": "해외 사례", 
    "Theories": "학술 이론", 
    "Stakeholders": "이해관계자" 
  },
  ja: { 
    "Statistics": "統計データ", 
    "PublicOpinion": "世論調査", 
    "DomesticCases": "国内事例", 
    "InternationalCases": "海外事例", 
    "Theories": "学術理論", 
    "Stakeholders": "利害関係者" 
  },
  "zh-CN": { "Statistics": "统计数据", "PublicOpinion": "公众舆论", "DomesticCases": "国内案例", "InternationalCases": "国际案例", "Theories": "学术理论", "Stakeholders": "利益相关者" },
  "zh-TW": { "Statistics": "統計數據", "PublicOpinion": "公眾輿論", "DomesticCases": "國內案例", "InternationalCases": "國際案例", "Theories": "學術理論", "Stakeholders": "利益相關者" },
  es: { "Statistics": "Estadísticas", "PublicOpinion": "Opinión Pública", "DomesticCases": "Casos Nacionales", "InternationalCases": "Casos Internacionales", "Theories": "Teorías Académicas", "Stakeholders": "Partes Interesadas" },
  fr: { "Statistics": "Statistiques", "PublicOpinion": "Opinion Publique", "DomesticCases": "Cas Nationaux", "InternationalCases": "Cas Internationaux", "Theories": "Théories Académiques", "Stakeholders": "Parties Prenantes" },
  de: { "Statistics": "Statistiken", "PublicOpinion": "Öffentliche Meinung", "DomesticCases": "Inländische Fälle", "InternationalCases": "Internationale Fälle", "Theories": "Akademische Theorien", "Stakeholders": "Interessengruppen" },
  it: { "Statistics": "Statistiche", "PublicOpinion": "Opinione Pubblica", "DomesticCases": "Casi Nazionali", "InternationalCases": "Casi Internazionali", "Theories": "Teorie Accademiche", "Stakeholders": "Stakeholder" },
  pt: { "Statistics": "Estatísticas", "PublicOpinion": "Opinião Pública", "DomesticCases": "Casos Nacionais", "InternationalCases": "Casos Internacionais", "Theories": "Teorias Acadêmicas", "Stakeholders": "Partes Interessadas" },
  ru: { "Statistics": "Статистика", "PublicOpinion": "Общественное мнение", "DomesticCases": "Внутренние дела", "InternationalCases": "Международные дела", "Theories": "Академические теории", "Stakeholders": "Заинтересованные стороны" },
  hi: { "Statistics": "सांख्यिकी", "PublicOpinion": "जनमत", "DomesticCases": "घरेलू मामले", "InternationalCases": "अंतर्राष्ट्रीय मामले", "Theories": "शैक्षणिक सिद्धांत", "Stakeholders": "हितधारक" },
  ar: { "Statistics": "إحصائيات", "PublicOpinion": "رأي عام", "DomesticCases": "قضايا محلية", "InternationalCases": "قضايا دولية", "Theories": "نظريات أكاديمية", "Stakeholders": "أصحاب المصلحة" },
  bn: { "Statistics": "পরিসংখ্যান", "PublicOpinion": "জনমত", "DomesticCases": "অভ্যন্তরীণ মামলা", "InternationalCases": "আন্তর্জাতিক মামলা", "Theories": "একাডেমিক তত্ত্ব", "Stakeholders": "অংশীজন" },
  id: { "Statistics": "Statistik", "PublicOpinion": "Opini Publik", "DomesticCases": "Kasus Domestik", "InternationalCases": "Kasus Internasional", "Theories": "Teori Akademik", "Stakeholders": "Pemangku Kepentingan" },
};

export const getSectorTranslation = (lang: string, sector: string) => {
  return SECTOR_TRANSLATIONS[lang]?.[sector] || SECTOR_TRANSLATIONS['en'][sector] || sector;
};

// Base text structure for type safety
const BASE_TEXTS = {
  title: "BiasBreaker",
  subtitle: "Political Debate Simulator (CEDA Format)",
  methodology: "Methodology",
  liveStatus: "Live Status",
  footer: "BiasBreaker AI. Built to challenge confirmation bias.",
  heroTitle: "Break Your Confirmation Bias.",
  heroDesc: "Don't let algorithms reinforce your confirmation bias anymore.\nEnter a controversial political or social topic and become the moderator and observer of the debate. \nGain unbiased information through rigorous debate by AI agents.",
  placeholder: "e.g. Should Universal Basic Income be implemented?",
  simulateBtn: "Simulate",
  suggestions: ["Nuclear Energy", "AI Regulation", "Healthcare Reform"],
  tryLabel: "Try:",
  runningIn: "Relevant Country:",
  timeframe: "Timeframe:",
  stopBtn: "Stop Simulation",
  newTopicBtn: "New Topic",
  tabDebate: "Debate Stream",
  tabAnalysis: "Meta Analysis",
  allSectors: "All Sectors",
  crossExamTitle: "Cross-Examination Phase",
  keyAgreements: "Key Agreements",
  keyDisagreements: "Key Disagreements",
  sectorAnalysis: "Sector Analysis",
  reflection: "Reflection Module",
  framingTitle: "Let's Define the Debate",
  framingDesc: "Chat with our agent to refine the topic, scope, and definition before starting.",
  chatPlaceholder: "e.g. Focus only on the US, or change the timeframe...",
  btnSend: "Send",
  liveDraft: "Debate Draft",
  definition: "Definition & Context",
  proStance: "Pro Position",
  conStance: "Con Position",
  btnStart: "Start Debate",
  chatWelcome: "I've drafted a debate topic based on your input. Is this what you had in mind? We can refine the scope, country, or definition via chat.",
  followUpTitle: "Deep Dive / Follow Up",
  followUpDesc: "Ask a question to trigger a new round of debate arguments focused on your specific topic.",
  followUpPlaceholder: "e.g. What about the impact on small businesses specifically?",
  btnRedebate: "Ask & Debate",
  userQuestion: "User Question",
  generatingRound: "Agents are debating your question...",
  framing: "Issue Framer",
  researching: "Researching",
  researchComplete: "Evidence Collection Complete",
  btnProceedDebate: "Start Debate Simulation",
  arguing_pro: "Pro Constructive",
  cx_con: "Con CX",
  arguing_con: "Con Constructive",
  cx_pro: "Pro CX",
  rebuttal_con: "Rebuttal Phase",
  rebuttal_pro: "Rebuttal Phase",
  analyzing: "Analysis",
  analyzing_loading: "Generating Meta Analysis Report",
  toggleEvidence: "Evidence Board",
  noEvidence: "No evidence gathered yet.",
  evidenceHint: "Evidence will appear here once the debate starts.",
  // Control Bar
  nextStep: "Next",
  pause: "Pause",
  resume: "Resume",
  autoPlay: "Auto-play"
};

export const TEXTS: Record<string, typeof BASE_TEXTS> = {
  en: BASE_TEXTS,
  ko: {
    title: "BiasBreaker",
    subtitle: "정치 토론 시뮬레이터 (CEDA 형식)",
    methodology: "방법론",
    liveStatus: "상태",
    footer: "BiasBreaker AI. 확증 편향을 깨기 위해 만들어졌습니다.",
    heroTitle: "확증 편향을 깨부수세요.",
    heroDesc: "더이상 당신의 알고리즘에 의해 확증편향이 강화되도록 두지 마세요.\n논란이 되는 정치적, 사회적 주제를 입력하고 토론회의 사회자이자 관찰자가 되어보세요.\nAI 에이전트들의 엄격한 토론을 통해 어느 쪽에도 치우쳐지지 않은 정보를 얻으세요.",
    placeholder: "예: 기본소득을 도입해야 하는가?",
    simulateBtn: "시뮬레이션 시작",
    suggestions: ["원자력 발전", "AI 규제", "의료 개혁"],
    tryLabel: "예시:",
    runningIn: "관련 국가:",
    timeframe: "기간:",
    stopBtn: "시뮬레이션 중지",
    newTopicBtn: "새로운 주제",
    tabDebate: "실시간 토론 스트림",
    tabAnalysis: "메타 분석",
    allSectors: "전체 영역",
    crossExamTitle: "상호 심문 단계",
    keyAgreements: "주요 합의점",
    keyDisagreements: "주요 쟁점 및 불일치",
    sectorAnalysis: "영역별 분석",
    reflection: "성찰 모듈",
    framingTitle: "토론 주제 정의하기",
    framingDesc: "토론을 시작하기 전, 에이전트와 대화하여 주제, 범위, 정의를 명확히 하세요.",
    chatPlaceholder: "예: 한국 상황에만 맞춰줘, 혹은 기간을 최근 5년으로...",
    btnSend: "전송",
    liveDraft: "토론 초안",
    definition: "정의 및 맥락",
    proStance: "찬성 측 핵심 입장",
    conStance: "반대 측 핵심 입장",
    btnStart: "토론 시작하기",
    chatWelcome: "입력하신 내용을 바탕으로 토론 주제를 잡아보았습니다. 원하시는 방향이 맞나요? 채팅을 통해 범위나 정의를 수정할 수 있습니다.",
    followUpTitle: "심층 질문 및 추가 토론",
    followUpDesc: "궁금한 점을 질문하면 해당 주제에 대해 찬성/반대 측이 추가적인 주장과 반론을 펼칩니다.",
    followUpPlaceholder: "예: 이 정책이 자영업자에게 미치는 영향에 대해서만 다시 토론해줘.",
    btnRedebate: "질문하기",
    userQuestion: "사용자 질문",
    generatingRound: "질문에 대해 에이전트들이 토론 중입니다...",
    framing: "쟁점 설정",
    researching: "중립 연구",
    researchComplete: "증거 수집 완료",
    btnProceedDebate: "본격 토론 시작하기",
    arguing_pro: "찬성 입론 (Pro)",
    cx_con: "반대 교차조사 (CX)",
    arguing_con: "반대 입론 (Con)",
    cx_pro: "찬성 교차조사 (CX)",
    rebuttal_con: "상호 반론",
    rebuttal_pro: "상호 반론",
    analyzing: "메타 분석",
    analyzing_loading: "메타 분석 보고서 생성중",
    toggleEvidence: "증거 보드",
    noEvidence: "수집된 증거가 없습니다.",
    evidenceHint: "토론이 시작되면 이곳에 증거가 표시됩니다.",
    nextStep: "다음",
    pause: "일시정지",
    resume: "다시 시작",
    autoPlay: "자동 재생"
  },
  ja: {
    title: "BiasBreaker",
    subtitle: "政治討論シミュレーター (CEDA形式)",
    methodology: "方法論",
    liveStatus: "ステータス",
    footer: "BiasBreaker AI. 確証バイアスを打破するために。",
    heroTitle: "確証バイアスを打ち破れ。",
    heroDesc: "アルゴリズムによって確証バイアスが強化されるのを、これ以上放置しないでください。\n議論を呼ぶ政治的・社会的なトピックを入力し、討論の司会者兼観察者になってみましょう。\nAIエージェントによる厳格な討論を通じて、偏りのない情報を手に入れましょう。",
    placeholder: "例：ベーシックインカムを導入すべきか？",
    simulateBtn: "シミュレーション開始",
    suggestions: ["原子力発電", "AI規制", "医療制度改革"],
    tryLabel: "例：",
    runningIn: "関連国：",
    timeframe: "期間：",
    stopBtn: "停止",
    newTopicBtn: "新しいトピック",
    tabDebate: "リアルタイム討論",
    tabAnalysis: "メタ分析",
    allSectors: "全領域",
    crossExamTitle: "反対尋問フェーズ",
    keyAgreements: "主な合意点",
    keyDisagreements: "主な対立点",
    sectorAnalysis: "領域別分析",
    reflection: "リフレクション（省察）",
    framingTitle: "討論テーマの定義",
    framingDesc: "開始する前に、エージェントとチャットしてトピック、範囲、定義を明確にしましょう。",
    chatPlaceholder: "例：日本国内に限定して、または過去5年に絞って...",
    btnSend: "送信",
    liveDraft: "討論ドラフト",
    definition: "定義と文脈",
    proStance: "肯定側の立場",
    conStance: "否定側の立場",
    btnStart: "討論を開始",
    chatWelcome: "入力内容に基づいて討論トピックを草案しました。この方向性でよろしいですか？チャットで範囲や定義を修正できます。",
    followUpTitle: "深堀り / フォローアップ",
    followUpDesc: "質問をすることで、その特定のトピックに焦点を当てた新しいラウンドの議論を開始できます。",
    followUpPlaceholder: "例：中小企業への影響について詳しく議論して。",
    btnRedebate: "質問する",
    userQuestion: "ユーザーの質問",
    generatingRound: "エージェントが質問について討論中...",
    framing: "論点設定",
    researching: "リサーチ中",
    researchComplete: "証拠収集完了",
    btnProceedDebate: "討論シミュレーション開始",
    arguing_pro: "肯定側立論 (Pro)",
    cx_con: "否定側反対尋問 (CX)",
    arguing_con: "否定側立論 (Con)",
    cx_pro: "肯定側反対尋問 (CX)",
    rebuttal_con: "反駁フェーズ",
    rebuttal_pro: "反駁フェーズ",
    analyzing: "分析中",
    analyzing_loading: "メタ分析レポートを作成中",
    toggleEvidence: "証拠ボード",
    noEvidence: "収集された証拠はまだありません。",
    evidenceHint: "討論が始まるとここに証拠が表示されます。",
    nextStep: "次へ",
    pause: "一時停止",
    resume: "再開",
    autoPlay: "自動再生"
  },
  "zh-CN": {
    title: "BiasBreaker",
    subtitle: "政治辩论模拟器 (CEDA 格式)",
    methodology: "方法论",
    liveStatus: "实时状态",
    footer: "BiasBreaker AI. 旨在挑战确认偏误。",
    heroTitle: "打破你的确认偏见。",
    heroDesc: "不要再让算法强化你的确认偏见。\n输入一个有争议的政治或社会话题，成为辩论的主持人和观察者。\n通过 AI 代理的严谨辩论，获取不偏不倚的信息。",
    placeholder: "例如：是否应该实施全民基本收入？",
    simulateBtn: "开始模拟",
    suggestions: ["核能", "AI 监管", "医疗改革"],
    tryLabel: "尝试：",
    runningIn: "相关国家：",
    timeframe: "时间范围：",
    stopBtn: "停止模拟",
    newTopicBtn: "新话题",
    tabDebate: "实时辩论流",
    tabAnalysis: "元分析",
    allSectors: "所有领域",
    crossExamTitle: "交叉质询阶段",
    keyAgreements: "主要共识",
    keyDisagreements: "主要分歧",
    sectorAnalysis: "领域分析",
    reflection: "反思模块",
    framingTitle: "定义辩论主题",
    framingDesc: "在开始之前，与我们的代理聊天以完善主题、范围和定义。",
    chatPlaceholder: "例如：仅关注美国，或更改时间范围...",
    btnSend: "发送",
    liveDraft: "辩论草案",
    definition: "定义与背景",
    proStance: "正方立场",
    conStance: "反方立场",
    btnStart: "开始辩论",
    chatWelcome: "我已根据您的输入草拟了一个辩论主题。这是您想要的吗？我们可以通过聊天完善范围、国家或定义。",
    followUpTitle: "深入探讨 / 跟进",
    followUpDesc: "提出一个问题，以针对您的特定主题引发新一轮的辩论论证。",
    followUpPlaceholder: "例如：具体对小企业有什么影响？",
    btnRedebate: "提问并辩论",
    userQuestion: "用户提问",
    generatingRound: "代理正在辩论您的问题...",
    framing: "问题构建",
    researching: "研究中",
    researchComplete: "证据收集完成",
    btnProceedDebate: "开始辩论",
    arguing_pro: "正方立论",
    cx_con: "反方交叉质询",
    arguing_con: "反方立论",
    cx_pro: "正方交叉质询",
    rebuttal_con: "反驳阶段",
    rebuttal_pro: "反驳阶段",
    analyzing: "分析中",
    analyzing_loading: "正在生成元分析报告",
    toggleEvidence: "证据板",
    noEvidence: "尚未收集到证据。",
    evidenceHint: "辩论开始后，证据将显示在此处。",
    nextStep: "下一步",
    pause: "暂停",
    resume: "继续",
    autoPlay: "自动播放"
  },
  "zh-TW": {
    title: "BiasBreaker",
    subtitle: "政治辯論模擬器 (CEDA 格式)",
    methodology: "方法論",
    liveStatus: "實時狀態",
    footer: "BiasBreaker AI. 旨在挑戰確認偏誤。",
    heroTitle: "打破你的確認偏見。",
    heroDesc: "不要再讓演算法強化你的確認偏見。\n輸入一個有爭議的政治或社會話題，成為辯論的主持人和觀察者。\n透過 AI 代理的嚴謹辯論，獲取不偏不倚的資訊。",
    placeholder: "例如：是否應該實施全民基本收入？",
    simulateBtn: "開始模擬",
    suggestions: ["核能", "AI 監管", "醫療改革"],
    tryLabel: "嘗試：",
    runningIn: "相關國家：",
    timeframe: "時間範圍：",
    stopBtn: "停止模擬",
    newTopicBtn: "新話題",
    tabDebate: "實時辯論流",
    tabAnalysis: "元分析",
    allSectors: "所有領域",
    crossExamTitle: "交叉質詢階段",
    keyAgreements: "主要共識",
    keyDisagreements: "主要分歧",
    sectorAnalysis: "領域分析",
    reflection: "反思模組",
    framingTitle: "定義辯論主題",
    framingDesc: "在開始之前，與我們的代理聊天以完善主題、範圍和定義。",
    chatPlaceholder: "例如：僅關注美國，或更改時間範圍...",
    btnSend: "發送",
    liveDraft: "辯論草案",
    definition: "定義與背景",
    proStance: "正方立場",
    conStance: "反方立場",
    btnStart: "開始辯論",
    chatWelcome: "我已根據您的輸入草擬了一個辯論主題。這是您想要的嗎？我們可以透過聊天完善範圍、國家或定義。",
    followUpTitle: "深入探討 / 跟進",
    followUpDesc: "提出一個問題，以針對您的特定主題引發新一輪的辯論論證。",
    followUpPlaceholder: "例如：具體對小企業有什麼影響？",
    btnRedebate: "提問並辯論",
    userQuestion: "用戶提問",
    generatingRound: "代理正在辯論您的問題...",
    framing: "問題構建",
    researching: "研究中",
    researchComplete: "證據收集完成",
    btnProceedDebate: "開始辯論",
    arguing_pro: "正方立論",
    cx_con: "反方交叉質詢",
    arguing_con: "反方立論",
    cx_pro: "正方交叉質詢",
    rebuttal_con: "反駁階段",
    rebuttal_pro: "反駁階段",
    analyzing: "分析中",
    analyzing_loading: "正在生成元分析報告",
    toggleEvidence: "證據板",
    noEvidence: "尚未收集到證據。",
    evidenceHint: "辯論開始後，證據將顯示在此處。",
    nextStep: "下一步",
    pause: "暫停",
    resume: "繼續",
    autoPlay: "自動播放"
  },
  es: {
    title: "BiasBreaker",
    subtitle: "Simulador de Debate Político (Formato CEDA)",
    methodology: "Metodología",
    liveStatus: "Estado en vivo",
    footer: "BiasBreaker AI. Creado para desafiar el sesgo de confirmación.",
    heroTitle: "Rompe tu sesgo de confirmación.",
    heroDesc: "No dejes que los algoritmos sigan reforzando tu sesgo de confirmación.\nIntroduce un tema político o social controvertido y conviértete en el moderador y observador del debate. \nObtén información imparcial a través de un riguroso debate de agentes de IA.",
    placeholder: "ej. ¿Debería implementarse la Renta Básica Universal?",
    simulateBtn: "Simular",
    suggestions: ["Energía Nuclear", "Regulación de IA", "Reforma Sanitaria"],
    tryLabel: "Prueba:",
    runningIn: "País Relevante:",
    timeframe: "Periodo:",
    stopBtn: "Detener Simulación",
    newTopicBtn: "Nuevo Tema",
    tabDebate: "Transmisión del Debate",
    tabAnalysis: "Metaanálisis",
    allSectors: "Todos los Sectores",
    crossExamTitle: "Fase de Interrogatorio",
    keyAgreements: "Acuerdos Clave",
    keyDisagreements: "Desacuerdos Clave",
    sectorAnalysis: "Análisis por Sector",
    reflection: "Módulo de Reflexión",
    framingTitle: "Definamos el Debate",
    framingDesc: "Chatea con nuestro agente para refinar el tema, el alcance y la definición antes de comenzar.",
    chatPlaceholder: "ej. Centrarse solo en EE. UU., o cambiar el periodo...",
    btnSend: "Enviar",
    liveDraft: "Borrador del Debate",
    definition: "Definición y Contexto",
    proStance: "Postura A Favor",
    conStance: "Postura En Contra",
    btnStart: "Iniciar Debate",
    chatWelcome: "He redactado un tema de debate basado en tu entrada. ¿Es esto lo que tenías en mente? Podemos refinar el alcance, el país o la definición a través del chat.",
    followUpTitle: "Profundizar / Seguimiento",
    followUpDesc: "Haz una pregunta para desencadenar una nueva ronda de argumentos de debate centrados en tu tema específico.",
    followUpPlaceholder: "ej. ¿Qué pasa con el impacto en las pequeñas empresas específicamente?",
    btnRedebate: "Preguntar y Debatir",
    userQuestion: "Pregunta del Usuario",
    generatingRound: "Los agentes están debatiendo tu pregunta...",
    framing: "Enmarcado del Problema",
    researching: "Investigando",
    researchComplete: "Colección de Pruebas Completa",
    btnProceedDebate: "Iniciar Debate",
    arguing_pro: "Constructivo A favor",
    cx_con: "Interrogatorio en Contra",
    arguing_con: "Constructivo en Contra",
    cx_pro: "Interrogatorio A favor",
    rebuttal_con: "Fase de Refutación",
    rebuttal_pro: "Fase de Refutación",
    analyzing: "Analizando",
    analyzing_loading: "Generando informe de metaanálisis",
    toggleEvidence: "Tablero de Evidencias",
    noEvidence: "Aún no se ha reunido evidencia.",
    evidenceHint: "La evidencia aparecerá aquí una vez que comience el debate.",
    nextStep: "Siguiente",
    pause: "Pausa",
    resume: "Reanudar",
    autoPlay: "Reproducción automática"
  },
  fr: {
    title: "BiasBreaker",
    subtitle: "Simulateur de Débat Politique (Format CEDA)",
    methodology: "Méthodologie",
    liveStatus: "Statut en direct",
    footer: "BiasBreaker AI. Conçu pour défier le biais de confirmation.",
    heroTitle: "Brisez votre biais de confirmation.",
    heroDesc: "Ne laissez plus les algorithmes renforcer votre biais de confirmation.\nEntrez un sujet politique ou social controversé et devenez le modérateur et l'observateur du débat. \nObtenez des informations impartiales grâce au débat rigoureux des agents IA.",
    placeholder: "ex. Le revenu de base universel devrait-il être mis en œuvre ?",
    simulateBtn: "Simuler",
    suggestions: ["Énergie Nucléaire", "Régulation de l'IA", "Réforme de la Santé"],
    tryLabel: "Essayez :",
    runningIn: "Pays Concerné :",
    timeframe: "Période :",
    stopBtn: "Arrêter la Simulation",
    newTopicBtn: "Nouveau Sujet",
    tabDebate: "Flux du Débat",
    tabAnalysis: "Méta-analyse",
    allSectors: "Tous les Secteurs",
    crossExamTitle: "Phase de Contre-Interrogatoire",
    keyAgreements: "Accords Clés",
    keyDisagreements: "Désaccords Clés",
    sectorAnalysis: "Analyse par Secteur",
    reflection: "Module de Réflexion",
    framingTitle: "Définissons le Débat",
    framingDesc: "Discutez avec notre agent pour affiner le sujet, la portée et la définition avant de commencer.",
    chatPlaceholder: "ex. Se concentrer uniquement sur la France, ou changer la période...",
    btnSend: "Envoyer",
    liveDraft: "Brouillon du Débat",
    definition: "Définition et Contexte",
    proStance: "Position Pour",
    conStance: "Position Contre",
    btnStart: "Commencer le Débat",
    chatWelcome: "J'ai rédigé un sujet de débat basé sur votre entrée. Est-ce ce que vous aviez en tête ? Nous pouvons affiner la portée, le pays ou la définition via le chat.",
    followUpTitle: "Approfondissement / Suivi",
    followUpDesc: "Posez une question pour déclencher une nouvelle série d'arguments de débat axés sur votre sujet spécifique.",
    followUpPlaceholder: "ex. Qu'en est-il de l'impact sur les petites entreprises spécifiquement ?",
    btnRedebate: "Demander et Débattre",
    userQuestion: "Question de l'Utilisateur",
    generatingRound: "Les agents débattent de votre question...",
    framing: "Cadrage du Problème",
    researching: "Recherche",
    researchComplete: "Collecte de Preuves Terminée",
    btnProceedDebate: "Lancer le Débat",
    arguing_pro: "Constructif Pour",
    cx_con: "Contre-Interrogatoire Contre",
    arguing_con: "Constructif Contre",
    cx_pro: "Contre-Interrogatoire Pour",
    rebuttal_con: "Phase de Réfutation",
    rebuttal_pro: "Phase de Réfutation",
    analyzing: "Analyse",
    analyzing_loading: "Génération du rapport de méta-analyse",
    toggleEvidence: "Tableau de Preuves",
    noEvidence: "Aucune preuve rassemblée pour l'instant.",
    evidenceHint: "Les preuves apparaîtront ici une fois le débat commencé.",
    nextStep: "Suivant",
    pause: "Pause",
    resume: "Reprendre",
    autoPlay: "Lecture auto"
  },
  de: {
    title: "BiasBreaker",
    subtitle: "Politischer Debattensimulator (CEDA-Format)",
    methodology: "Methodik",
    liveStatus: "Live-Status",
    footer: "BiasBreaker AI. Entwickelt, um den Bestätigungsfehler herauszufordern.",
    heroTitle: "Durchbrechen Sie Ihren Bestätigungsfehler.",
    heroDesc: "Lassen Sie nicht länger zu, dass Algorithmen Ihren Bestätigungsfehler verstärken.\nGeben Sie ein kontroverses politisches oder soziales Thema ein und werden Sie zum Moderator und Beobachter der Debatte. \nGewinnen Sie unvoreingenommene Informationen durch die strenge Debatte von KI-Agenten.",
    placeholder: "z.B. Sollte ein bedingungsloses Grundeinkommen eingeführt werden?",
    simulateBtn: "Simulieren",
    suggestions: ["Kernenergie", "KI-Regulierung", "Gesundheitsreform"],
    tryLabel: "Versuchen Sie:",
    runningIn: "Relevantes Land:",
    timeframe: "Zeitrahmen:",
    stopBtn: "Simulation stoppen",
    newTopicBtn: "Neues Thema",
    tabDebate: "Debatten-Stream",
    tabAnalysis: "Meta-Analyse",
    allSectors: "Alle Sektoren",
    crossExamTitle: "Kreuzverhör-Phase",
    keyAgreements: "Wichtige Übereinstimmungen",
    keyDisagreements: "Wichtige Unstimmigkeiten",
    sectorAnalysis: "Sektoranalyse",
    reflection: "Reflexionsmodul",
    framingTitle: "Lassen Sie uns die Debatte definieren",
    framingDesc: "Chatten Sie mit unserem Agenten, um Thema, Umfang und Definition zu verfeinern, bevor Sie beginnen.",
    chatPlaceholder: "z.B. Konzentrieren Sie sich nur auf Deutschland oder ändern Sie den Zeitrahmen...",
    btnSend: "Senden",
    liveDraft: "Debattenentwurf",
    definition: "Definition & Kontext",
    proStance: "Pro-Position",
    conStance: "Contra-Position",
    btnStart: "Debatte beginnen",
    chatWelcome: "Ich habe basierend auf Ihrer Eingabe ein Debattenthema entworfen. Ist es das, was Sie sich vorgestellt haben? Wir können Umfang, Land oder Definition per Chat verfeinern.",
    followUpTitle: "Vertiefung / Nachverfolgung",
    followUpDesc: "Stellen Sie eine Frage, um eine neue Runde von Debattenargumenten zu Ihrem spezifischen Thema auszulösen.",
    followUpPlaceholder: "z.B. Was ist speziell mit den Auswirkungen auf kleine Unternehmen?",
    btnRedebate: "Fragen & Debattieren",
    userQuestion: "Benutzerfrage",
    generatingRound: "Agenten debattieren Ihre Frage...",
    framing: "Themenformulierung",
    researching: "Recherchieren",
    researchComplete: "Beweissammlung Abgeschlossen",
    btnProceedDebate: "Debatte Starten",
    arguing_pro: "Pro Konstruktiv",
    cx_con: "Contra Kreuzverhör",
    arguing_con: "Contra Konstruktiv",
    cx_pro: "Pro Kreuzverhör",
    rebuttal_con: "Widerlegungsphase",
    rebuttal_pro: "Widerlegungsphase",
    analyzing: "Analysieren",
    analyzing_loading: "Generiere Meta-Analyse-Bericht",
    toggleEvidence: "Beweis-Board",
    noEvidence: "Noch keine Beweise gesammelt.",
    evidenceHint: "Beweise erscheinen hier, sobald die Debatte beginnt.",
    nextStep: "Weiter",
    pause: "Pause",
    resume: "Fortsetzen",
    autoPlay: "Autoplay"
  },
  it: {
    title: "BiasBreaker",
    subtitle: "Simulatore di Dibattito Politico (Formato CEDA)",
    methodology: "Metodologia",
    liveStatus: "Stato in Diretta",
    footer: "BiasBreaker AI. Costruito per sfidare il bias di conferma.",
    heroTitle: "Rompi il tuo Bias di Conferma.",
    heroDesc: "Non lasciare che gli algoritmi rafforzino più il tuo bias di conferma.\nInserisci un argomento politico o sociale controverso e diventa il moderatore e osservatore del dibattito.\nOttieni informazioni imparziali attraverso un dibattito rigoroso di agenti AI.",
    placeholder: "es. Si dovrebbe implementare il Reddito di Base Universale?",
    simulateBtn: "Simula",
    suggestions: ["Energia Nucleare", "Regolamentazione AI", "Riforma Sanitaria"],
    tryLabel: "Prova:",
    runningIn: "Paese Rilevante:",
    timeframe: "Periodo:",
    stopBtn: "Ferma Simulazione",
    newTopicBtn: "Nuovo Argomento",
    tabDebate: "Flusso Dibattito",
    tabAnalysis: "Meta Analisi",
    allSectors: "Tutti i Settori",
    crossExamTitle: "Fase di Controesame",
    keyAgreements: "Accordi Chiave",
    keyDisagreements: "Disaccordi Chiave",
    sectorAnalysis: "Analisi per Settore",
    reflection: "Modulo di Riflessione",
    framingTitle: "Definiamo il Dibattito",
    framingDesc: "Chatta con il nostro agente per perfezionare l'argomento, l'ambito e la definizione prima di iniziare.",
    chatPlaceholder: "es. Concentrati solo sull'Italia, o cambia il periodo...",
    btnSend: "Invia",
    liveDraft: "Bozza Dibattito",
    definition: "Definizione e Contesto",
    proStance: "Posizione Pro",
    conStance: "Posizione Contro",
    btnStart: "Inizia Dibattito",
    chatWelcome: "Ho abbozzato un argomento di dibattito basato sul tuo input. È quello che avevi in mente? Possiamo perfezionare l'ambito, il paese o la definizione via chat.",
    followUpTitle: "Approfondimento / Follow Up",
    followUpDesc: "Fai una domanda per attivare un nuovo round di argomenti di dibattito focalizzati sul tuo argomento specifico.",
    followUpPlaceholder: "es. E l'impatto sulle piccole imprese specificamente?",
    btnRedebate: "Chiedi e Dibatti",
    userQuestion: "Domanda Utente",
    generatingRound: "Gli agenti stanno dibattendo la tua domanda...",
    framing: "Inquadramento Problema",
    researching: "Ricerca",
    researchComplete: "Raccolta Prove Completata",
    btnProceedDebate: "Avvia Simulazione Dibattito",
    arguing_pro: "Costruttivo Pro",
    cx_con: "Controesame Contro",
    arguing_con: "Costruttivo Contro",
    cx_pro: "Controesame Pro",
    rebuttal_con: "Fase di Confutazione",
    rebuttal_pro: "Fase di Confutazione",
    analyzing: "Analisi",
    analyzing_loading: "Generazione Report Meta Analisi",
    toggleEvidence: "Bacheca Prove",
    noEvidence: "Nessuna prova raccolta ancora.",
    evidenceHint: "Le prove appariranno qui una volta iniziato il dibattito.",
    nextStep: "Avanti",
    pause: "Pausa",
    resume: "Riprendi",
    autoPlay: "Auto-play"
  },
  pt: {
    title: "BiasBreaker",
    subtitle: "Simulador de Debate Político (Formato CEDA)",
    methodology: "Metodologia",
    liveStatus: "Status ao Vivo",
    footer: "BiasBreaker AI. Construído para desafiar o viés de confirmação.",
    heroTitle: "Quebre seu Viés de Confirmação.",
    heroDesc: "Não deixe que os algoritmos reforcem seu viés de confirmação.\nInsira um tópico político ou social controverso e torne-se o moderador e observador do debate.\nObtenha informações imparciais através de um debate rigoroso por agentes de IA.",
    placeholder: "ex. A Renda Básica Universal deve ser implementada?",
    simulateBtn: "Simular",
    suggestions: ["Energia Nuclear", "Regulação de IA", "Reforma da Saúde"],
    tryLabel: "Tente:",
    runningIn: "País Relevante:",
    timeframe: "Período:",
    stopBtn: "Parar Simulação",
    newTopicBtn: "Novo Tópico",
    tabDebate: "Fluxo de Debate",
    tabAnalysis: "Meta Análise",
    allSectors: "Todos os Setores",
    crossExamTitle: "Fase de Contrainterrogatório",
    keyAgreements: "Acordos Chave",
    keyDisagreements: "Desacordos Chave",
    sectorAnalysis: "Análise Setorial",
    reflection: "Módulo de Reflexão",
    framingTitle: "Vamos Definir o Debate",
    framingDesc: "Converse com nosso agente para refinar o tópico, escopo e definição antes de começar.",
    chatPlaceholder: "ex. Foque apenas no Brasil, ou mude o período...",
    btnSend: "Enviar",
    liveDraft: "Rascunho do Debate",
    definition: "Definição e Contexto",
    proStance: "Posição A Favor",
    conStance: "Posição Contra",
    btnStart: "Iniciar Debate",
    chatWelcome: "Redigi um tópico de debate com base na sua entrada. É isso que você tinha em mente? Podemos refinar o escopo, país ou definição via chat.",
    followUpTitle: "Aprofundamento / Acompanhamento",
    followUpDesc: "Faça uma pergunta para acionar uma nova rodada de argumentos de debate focados no seu tópico específico.",
    followUpPlaceholder: "ex. E o impacto nas pequenas empresas especificamente?",
    btnRedebate: "Perguntar e Debater",
    userQuestion: "Pergunta do Usuário",
    generatingRound: "Agentes estão debatendo sua pergunta...",
    framing: "Enquadramento",
    researching: "Pesquisando",
    researchComplete: "Coleta de Evidências Completa",
    btnProceedDebate: "Iniciar Simulação de Debate",
    arguing_pro: "Construtivo Pró",
    cx_con: "Contrainterrogatório Contra",
    arguing_con: "Construtivo Contra",
    cx_pro: "Contrainterrogatório Pró",
    rebuttal_con: "Fase de Refutação",
    rebuttal_pro: "Fase de Refutação",
    analyzing: "Analisando",
    analyzing_loading: "Gerando Relatório de Meta Análise",
    toggleEvidence: "Quadro de Evidências",
    noEvidence: "Nenhuma evidência coletada ainda.",
    evidenceHint: "As evidências aparecerão aqui assim que o debate começar.",
    nextStep: "Próximo",
    pause: "Pausa",
    resume: "Continuar",
    autoPlay: "Reprodução Automática"
  },
  ru: {
    title: "BiasBreaker",
    subtitle: "Симулятор политических дебатов (формат CEDA)",
    methodology: "Методология",
    liveStatus: "Статус",
    footer: "BiasBreaker AI. Создан для борьбы с предвзятостью подтверждения.",
    heroTitle: "Разрушьте свою предвзятость.",
    heroDesc: "Не позволяйте алгоритмам усиливать вашу предвзятость подтверждения.\nВведите спорную политическую или социальную тему и станьте модератором и наблюдателем дебатов.\nПолучите непредвзятую информацию через строгие дебаты агентов ИИ.",
    placeholder: "напр. Следует ли вводить безусловный базовый доход?",
    simulateBtn: "Симулировать",
    suggestions: ["Ядерная энергия", "Регулирование ИИ", "Реформа здравоохранения"],
    tryLabel: "Попробуйте:",
    runningIn: "Страна:",
    timeframe: "Период:",
    stopBtn: "Остановить",
    newTopicBtn: "Новая тема",
    tabDebate: "Ход дебатов",
    tabAnalysis: "Мета-анализ",
    allSectors: "Все секторы",
    crossExamTitle: "Перекрестный допрос",
    keyAgreements: "Ключевые согласия",
    keyDisagreements: "Ключевые разногласия",
    sectorAnalysis: "Секторальный анализ",
    reflection: "Модуль рефлексии",
    framingTitle: "Определим дебаты",
    framingDesc: "Пообщайтесь с агентом, чтобы уточнить тему, объем и определение перед началом.",
    chatPlaceholder: "напр. Сосредоточьтесь только на России, или измените период...",
    btnSend: "Отправить",
    liveDraft: "Черновик дебатов",
    definition: "Определение и контекст",
    proStance: "Позиция За",
    conStance: "Позиция Против",
    btnStart: "Начать дебаты",
    chatWelcome: "Я составил тему дебатов на основе вашего ввода. Это то, что вы имели в виду? Мы можем уточнить объем, страну или определение через чат.",
    followUpTitle: "Углубление / Продолжение",
    followUpDesc: "Задайте вопрос, чтобы запустить новый раунд аргументов, сфокусированных на вашей конкретной теме.",
    followUpPlaceholder: "напр. А как насчет влияния на малый бизнес конкретно?",
    btnRedebate: "Спросить и обсудить",
    userQuestion: "Вопрос пользователя",
    generatingRound: "Агенты обсуждают ваш вопрос...",
    framing: "Формулировка",
    researching: "Исследование",
    researchComplete: "Сбор доказательств завершен",
    btnProceedDebate: "Запустить симуляцию",
    arguing_pro: "Конструктив За",
    cx_con: "Перекрестный допрос Против",
    arguing_con: "Конструктив Против",
    cx_pro: "Перекрестный допрос За",
    rebuttal_con: "Фаза опровержения",
    rebuttal_pro: "Фаза опровержения",
    analyzing: "Анализ",
    analyzing_loading: "Генерация отчета мета-анализа",
    toggleEvidence: "Доска доказательств",
    noEvidence: "Доказательства пока не собраны.",
    evidenceHint: "Доказательства появятся здесь после начала дебатов.",
    nextStep: "Далее",
    pause: "Пауза",
    resume: "Продолжить",
    autoPlay: "Авто"
  },
  hi: {
    title: "BiasBreaker",
    subtitle: "राजनीतिक बहस सिम्युलेटर (CEDA प्रारूप)",
    methodology: "कार्यप्रणाली",
    liveStatus: "लाइव स्थिति",
    footer: "BiasBreaker AI. पुष्टि पूर्वाग्रह को चुनौती देने के लिए बनाया गया।",
    heroTitle: "अपने पुष्टि पूर्वाग्रह को तोड़ें।",
    heroDesc: "एल्गोरिदम को अब अपने पुष्टि पूर्वाग्रह को मजबूत न करने दें।\nएक विवादास्पद राजनीतिक या सामाजिक विषय दर्ज करें और बहस के मध्यस्थ और पर्यवेक्षक बनें।\nAI एजेंटों द्वारा कठोर बहस के माध्यम से निष्पक्ष जानकारी प्राप्त करें।",
    placeholder: "उदा. क्या यूनिवर्सल बेसिक इनकम लागू की जानी चाहिए?",
    simulateBtn: "अनुकरण करें",
    suggestions: ["परमाणु ऊर्जा", "AI विनियमन", "स्वास्थ्य सेवा सुधार"],
    tryLabel: "कोशिश करें:",
    runningIn: "प्रासंगिक देश:",
    timeframe: "समय सीमा:",
    stopBtn: "सिमुलेशन रोकें",
    newTopicBtn: "नया विषय",
    tabDebate: "बहस स्ट्रीम",
    tabAnalysis: "मेटा विश्लेषण",
    allSectors: "सभी क्षेत्र",
    crossExamTitle: "जिरह चरण",
    keyAgreements: "मुख्य समझौते",
    keyDisagreements: "मुख्य असहमति",
    sectorAnalysis: "क्षेत्र विश्लेषण",
    reflection: "चिंतन मॉड्यूल",
    framingTitle: "आइए बहस को परिभाषित करें",
    framingDesc: "शुरू करने से पहले विषय, दायरे और परिभाषा को परिष्कृत करने के लिए हमारे एजेंट के साथ चैट करें।",
    chatPlaceholder: "उदा. केवल भारत पर ध्यान केंद्रित करें, या समय सीमा बदलें...",
    btnSend: "भेजें",
    liveDraft: "बहस मसौदा",
    definition: "परिभाषा और संदर्भ",
    proStance: "पक्ष स्थिति",
    conStance: "विपक्ष स्थिति",
    btnStart: "बहस शुरू करें",
    chatWelcome: "मैंने आपके इनपुट के आधार पर एक बहस का विषय तैयार किया है। क्या आप यही सोच रहे थे? हम चैट के माध्यम से दायरे, देश या परिभाषा को परिष्कृत कर सकते हैं।",
    followUpTitle: "गहराई में जाएं / फॉलो अप",
    followUpDesc: "अपने विशिष्ट विषय पर केंद्रित बहस के तर्कों का एक नया दौर शुरू करने के लिए एक प्रश्न पूछें।",
    followUpPlaceholder: "उदा. विशेष रूप से छोटे व्यवसायों पर प्रभाव के बारे में क्या?",
    btnRedebate: "पूछें और बहस करें",
    userQuestion: "उपयोगकर्ता प्रश्न",
    generatingRound: "एजेंट आपके प्रश्न पर बहस कर रहे हैं...",
    framing: "मुद्दा तैयार करना",
    researching: "शोध",
    researchComplete: "साक्ष्य संग्रह पूर्ण",
    btnProceedDebate: "बहस सिमुलेशन शुरू करें",
    arguing_pro: "रचनात्मक पक्ष",
    cx_con: "विपक्ष जिरह",
    arguing_con: "रचनात्मक विपक्ष",
    cx_pro: "पक्ष जिरह",
    rebuttal_con: "खंडन चरण",
    rebuttal_pro: "खंडन चरण",
    analyzing: "विश्लेषण",
    analyzing_loading: "मेटा विश्लेषण रिपोर्ट तैयार की जा रही है",
    toggleEvidence: "साक्ष्य बोर्ड",
    noEvidence: "अभी तक कोई साक्ष्य एकत्र नहीं किया गया है।",
    evidenceHint: "बहस शुरू होने पर साक्ष्य यहां दिखाई देंगे।",
    nextStep: "अगला",
    pause: "विराम",
    resume: "फिर शुरू करें",
    autoPlay: "ऑटो-प्ले"
  },
  ar: {
    title: "BiasBreaker",
    subtitle: "محاكي المناظرة السياسية (تنسيق CEDA)",
    methodology: "المنهجية",
    liveStatus: "الحالة المباشرة",
    footer: "BiasBreaker AI. صُمم لتحدي الانحياز التأكيدي.",
    heroTitle: "اكسر انحيازك التأكيدي.",
    heroDesc: "لا تدع الخوارزميات تعزز انحيازك التأكيدي بعد الآن.\nأدخل موضوعًا سياسيًا أو اجتماعيًا مثيرًا للجدل وكن المشرف والمراقب للمناظرة.\nاحصل على معلومات غير متحيزة من خلال مناظرة صارمة بواسطة وكلاء الذكاء الاصطناعي.",
    placeholder: "مثال: هل يجب تطبيق الدخل الأساسي الشامل؟",
    simulateBtn: "محاكاة",
    suggestions: ["الطاقة النووية", "تنظيم الذكاء الاصطناعي", "إصلاح الرعاية الصحية"],
    tryLabel: "جرب:",
    runningIn: "البلد المعني:",
    timeframe: "الإطار الزمني:",
    stopBtn: "إيقاف المحاكاة",
    newTopicBtn: "موضوع جديد",
    tabDebate: "بث المناظرة",
    tabAnalysis: "التحليل التلخيصي",
    allSectors: "جميع القطاعات",
    crossExamTitle: "مرحلة الاستجواب",
    keyAgreements: "الاتفاقات الرئيسية",
    keyDisagreements: "الخلافات الرئيسية",
    sectorAnalysis: "تحليل القطاع",
    reflection: "وحدة التأمل",
    framingTitle: "لنحدد المناظرة",
    framingDesc: "تحدث مع وكيلنا لتحسين الموضوع والنطاق والتعريف قبل البدء.",
    chatPlaceholder: "مثال: ركز فقط على مصر، أو غير الإطار الزمني...",
    btnSend: "إرسال",
    liveDraft: "مسودة المناظرة",
    definition: "التعريف والسياق",
    proStance: "موقف المؤيد",
    conStance: "موقف المعارض",
    btnStart: "بدء المناظرة",
    chatWelcome: "لقد قمت بصياغة موضوع مناظرة بناءً على مدخلاتك. هل هذا ما كنت تفكر فيه؟ يمكننا تحسين النطاق أو البلد أو التعريف عبر الدردشة.",
    followUpTitle: "تعمق / متابعة",
    followUpDesc: "اطرح سؤالاً لبدء جولة جديدة من حجج المناظرة التي تركز على موضوعك المحدد.",
    followUpPlaceholder: "مثال: ماذا عن التأثير على الشركات الصغيرة تحديدًا؟",
    btnRedebate: "اسأل وناظر",
    userQuestion: "سؤال المستخدم",
    generatingRound: "الوكلاء يناقشون سؤالك...",
    framing: "تأطير القضية",
    researching: "البحث",
    researchComplete: "اكتمل جمع الأدلة",
    btnProceedDebate: "بدء محاكاة المناظرة",
    arguing_pro: "بناء المؤيد",
    cx_con: "استجواب المعارض",
    arguing_con: "بناء المعارض",
    cx_pro: "استجواب المؤيد",
    rebuttal_con: "مرحلة الدحض",
    rebuttal_pro: "مرحلة الدحض",
    analyzing: "تحليل",
    analyzing_loading: "جاري إنشاء تقرير التحليل التلخيصي",
    toggleEvidence: "لوحة الأدلة",
    noEvidence: "لم يتم جمع أي أدلة بعد.",
    evidenceHint: "ستظهر الأدلة هنا بمجرد بدء المناظرة.",
    nextStep: "التالي",
    pause: "إيقاف مؤقت",
    resume: "استئناف",
    autoPlay: "تشغيل تلقائي"
  },
  bn: {
    title: "BiasBreaker",
    subtitle: "রাজনৈতিক বিতর্ক সিমুলেটর (CEDA বিন্যাস)",
    methodology: "পদ্ধতি",
    liveStatus: "লাইভ স্ট্যাটাস",
    footer: "BiasBreaker AI. নিশ্চিতকরণ পক্ষপাত চ্যালেঞ্জ করার জন্য তৈরি।",
    heroTitle: "আপনার নিশ্চিতকরণ পক্ষপাত ভাঙুন।",
    heroDesc: "অ্যালগরিদমগুলিকে আপনার নিশ্চিতকরণ পক্ষপাতকে আর শক্তিশালী করতে দেবেন না।\nএকটি বিতর্কিত রাজনৈতিক বা সামাজিক বিষয় লিখুন এবং বিতর্কের মডারেটর এবং পর্যবেক্ষক হন।\nAI এজেন্টদের কঠোর বিতর্কের মাধ্যমে নিরপেক্ষ তথ্য পান।",
    placeholder: "উদাঃ সার্বজনীন মৌলিক আয় কি বাস্তবায়ন করা উচিত?",
    simulateBtn: "সিমুলেট",
    suggestions: ["পারমাণবিক শক্তি", "AI নিয়ন্ত্রণ", "স্বাস্থ্যসেবা সংস্কার"],
    tryLabel: "চেষ্টা করুন:",
    runningIn: "প্রাসঙ্গিক দেশ:",
    timeframe: "সময়কাল:",
    stopBtn: "সিমুলেশন বন্ধ করুন",
    newTopicBtn: "নতুন বিষয়",
    tabDebate: "বিতর্ক স্ট্রিম",
    tabAnalysis: "মেটা বিশ্লেষণ",
    allSectors: "সব সেক্টর",
    crossExamTitle: "জেরা পর্যায়",
    keyAgreements: "মূল চুক্তি",
    keyDisagreements: "মূল মতবিরোধ",
    sectorAnalysis: "সেক্টর বিশ্লেষণ",
    reflection: "প্রতিফলন মডিউল",
    framingTitle: "আসুন বিতর্ক সংজ্ঞায়িত করি",
    framingDesc: "শুরু করার আগে বিষয়, সুযোগ এবং সংজ্ঞা পরিমার্জন করতে আমাদের এজেন্টের সাথে চ্যাট করুন।",
    chatPlaceholder: "উদাঃ শুধুমাত্র বাংলাদেশের উপর ফোকাস করুন, বা সময়কাল পরিবর্তন করুন...",
    btnSend: "পাঠান",
    liveDraft: "বিতর্ক খসড়া",
    definition: "সংজ্ঞা এবং প্রসঙ্গ",
    proStance: "পক্ষে অবস্থান",
    conStance: "বিপক্ষে অবস্থান",
    btnStart: "বিতর্ক শুরু করুন",
    chatWelcome: "আমি আপনার ইনপুট উপর ভিত্তি করে একটি বিতর্ক বিষয় খসড়া করেছি। আপনি কি এইটাই ভাবছিলেন? আমরা চ্যাটের মাধ্যমে সুযোগ, দেশ বা সংজ্ঞা পরিমার্জন করতে পারি।",
    followUpTitle: "গভীর ডুব / ফলো আপ",
    followUpDesc: "আপনার নির্দিষ্ট বিষয়ের উপর দৃষ্টি নিবদ্ধ করে বিতর্কের যুক্তির একটি নতুন রাউন্ড ট্রিগার করতে একটি প্রশ্ন জিজ্ঞাসা করুন।",
    followUpPlaceholder: "উদাঃ বিশেষ করে ছোট ব্যবসার উপর প্রভাব সম্পর্কে কি?",
    btnRedebate: "জিজ্ঞাসা এবং বিতর্ক",
    userQuestion: "ব্যবহারকারীর প্রশ্ন",
    generatingRound: "এজেন্টরা আপনার প্রশ্ন নিয়ে বিতর্ক করছে...",
    framing: "সমস্যা ফ্রেমিং",
    researching: "গবেষণা",
    researchComplete: "প্রমাণ সংগ্রহ সম্পূর্ণ",
    btnProceedDebate: "বিতর্ক সিমুলেশন শুরু করুন",
    arguing_pro: "গঠনমূলক পক্ষ",
    cx_con: "বিপক্ষ জেরা",
    arguing_con: "গঠনমূলক বিপক্ষ",
    cx_pro: "পক্ষ জেরা",
    rebuttal_con: "খন্ডন পর্যায়",
    rebuttal_pro: "খন্ডন পর্যায়",
    analyzing: "বিশ্লেষণ করা হচ্ছে",
    analyzing_loading: "মেটা বিশ্লেষণ প্রতিবেদন তৈরি করা হচ্ছে",
    toggleEvidence: "প্রমাণ বোর্ড",
    noEvidence: "এখনও কোন প্রমাণ সংগ্রহ করা হয়নি।",
    evidenceHint: "বিতর্ক শুরু হলে প্রমাণ এখানে প্রদর্শিত হবে।",
    nextStep: "পরবর্তী",
    pause: "বিরতি",
    resume: "পুনরায় শুরু",
    autoPlay: "অটো-প্লে"
  },
  id: {
    title: "BiasBreaker",
    subtitle: "Simulator Debat Politik (Format CEDA)",
    methodology: "Metodologi",
    liveStatus: "Status Langsung",
    footer: "BiasBreaker AI. Dibangun untuk menantang bias konfirmasi.",
    heroTitle: "Hancurkan Bias Konfirmasi Anda.",
    heroDesc: "Jangan biarkan algoritme memperkuat bias konfirmasi Anda lagi.\nMasukkan topik politik atau sosial yang kontroversial dan jadilah moderator serta pengamat debat.\nDapatkan informasi yang tidak bias melalui debat yang ketat oleh agen AI.",
    placeholder: "mis. Haruskah Pendapatan Dasar Universal diterapkan?",
    simulateBtn: "Simulasikan",
    suggestions: ["Energi Nuklir", "Regulasi AI", "Reformasi Kesehatan"],
    tryLabel: "Coba:",
    runningIn: "Negara Terkait:",
    timeframe: "Jangka Waktu:",
    stopBtn: "Hentikan Simulasi",
    newTopicBtn: "Topik Baru",
    tabDebate: "Aliran Debat",
    tabAnalysis: "Meta Analisis",
    allSectors: "Semua Sektor",
    crossExamTitle: "Tahap Pemeriksaan Silang",
    keyAgreements: "Kesepakatan Utama",
    keyDisagreements: "Ketidaksepakatan Utama",
    sectorAnalysis: "Analisis Sektor",
    reflection: "Modul Refleksi",
    framingTitle: "Mari Definisikan Debat",
    framingDesc: "Mengobrol dengan agen kami untuk menyempurnakan topik, ruang lingkup, dan definisi sebelum memulai.",
    chatPlaceholder: "mis. Fokus hanya pada Indonesia, atau ubah jangka waktu...",
    btnSend: "Kirim",
    liveDraft: "Draf Debat",
    definition: "Definisi & Konteks",
    proStance: "Posisi Pro",
    conStance: "Posisi Kontra",
    btnStart: "Mulai Debat",
    chatWelcome: "Saya telah menyusun topik debat berdasarkan masukan Anda. Apakah ini yang Anda maksud? Kita dapat menyempurnakan ruang lingkup, negara, atau definisi melalui obrolan.",
    followUpTitle: "Pendalaman / Tindak Lanjut",
    followUpDesc: "Ajukan pertanyaan untuk memicu putaran baru argumen debat yang berfokus pada topik spesifik Anda.",
    followUpPlaceholder: "mis. Bagaimana dengan dampaknya pada usaha kecil secara khusus?",
    btnRedebate: "Tanya & Debat",
    userQuestion: "Pertanyaan Pengguna",
    generatingRound: "Agen sedang mendebatkan pertanyaan Anda...",
    framing: "Pembingkaian Masalah",
    researching: "Meneliti",
    researchComplete: "Pengumpulan Bukti Selesai",
    btnProceedDebate: "Mulai Simulasi Debat",
    arguing_pro: "Konstruktif Pro",
    cx_con: "Pemeriksaan Silang Kontra",
    arguing_con: "Konstruktif Kontra",
    cx_pro: "Pemeriksaan Silang Pro",
    rebuttal_con: "Tahap Sanggahan",
    rebuttal_pro: "Tahap Sanggahan",
    analyzing: "Menganalisis",
    analyzing_loading: "Membuat Laporan Meta Analisis",
    toggleEvidence: "Papan Bukti",
    noEvidence: "Belum ada bukti yang dikumpulkan.",
    evidenceHint: "Bukti akan muncul di sini setelah debat dimulai.",
    nextStep: "Lanjut",
    pause: "Jeda",
    resume: "Lanjutkan",
    autoPlay: "Putar Otomatis"
  },
};

export const getUIText = (lang: string) => {
  return TEXTS[lang] || TEXTS['en'];
};
